trigger:
- main
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
  
stages:
- stage: Test
  displayName: Test web app
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: 'Run tests'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --abort-on-container-exit --exit-code-from test'
