trigger:
- main
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
  
stages:
- stage: Test
  displayName: Test web app
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: 'Run tests'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --abort-on-container-exit --exit-code-from test'     
    - task: Npm@1
      displayName: 'npm test'
      inputs:
        command: custom
        verbose: false
        customCommand: 'run test:ci'
    - task: PublishTestResults@2
      displayName: 'Publish Test Results '
      inputs:
        testResultsFiles: test/junit.xml
      condition: succeededOrFailed()
    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage results'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      condition: succeededOrFailed()
 
