version: '3'

services:
  chromedriver:
    image: robcherry/docker-chromedriver
    privileged: true
    restart: always
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=''
    # ports:
    #   - '4444:4444'

  test:
    image: nixel2007/docker-selenium-side-runner
    # build:
    #   context: .
    volumes:
      - './sides:/sides'
      - './out:/root/out'
